# Generated by Django 5.0.7 on 2024-07-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='ReferenceBookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('reference_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.referencebook')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочника',
            },
        ),
        migrations.CreateModel(
            name='ReferenceBookElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=300)),
                ('reference_book_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='main.referencebookversion')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
        migrations.AddConstraint(
            model_name='referencebookversion',
            constraint=models.UniqueConstraint(fields=('reference_book_id', 'version'), name='unique_reference_book_id_and_version'),
        ),
        migrations.AddConstraint(
            model_name='referencebookelement',
            constraint=models.UniqueConstraint(fields=('reference_book_version_id', 'code'), name='unique_reference_book_version_id_and_code'),
        ),
    ]
